version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16 # Specify your node version
    commands:
      - echo "Installing frontend dependencies"
      - cd frontend
      - yarn # or yarn install

  build:
    commands:
      - echo "Building the frontend"
      - yarn build

artifacts:
  files:
    - "**/*"
  base-directory: "frontend/dist"
